=== liugnggh71/XML/XML/MyMoba/Steps.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="steps">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="repository_dir" minOccurs="0"/>
        <xs:element ref="macro_dir"/>
        <xs:element maxOccurs="unbounded" ref="group"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="macro_dir">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="alias_file" type="xs:NCName"/>
          <xs:attribute name="packingdir" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="prefix"/>
        <xs:element ref="subdir"/>
        <xs:element maxOccurs="unbounded" ref="step"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="subdir" type="xs:NMTOKEN"/>
  <xs:element name="prefix" type="xs:NMTOKEN"/>
  <xs:element name="repository_dir" type="xs:NMTOKEN"/>
  <xs:element name="step">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="aliss" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== liugnggh71/XML/XML/MyMoba/template/Steps.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../Steps.xsl"?>

<steps  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../Steps.xsd">
    <macro_dir packingdir='template.Alias' alias_file='template_ALIAS.sh'>template</macro_dir>
    <group>
        <prefix>FullProc</prefix>
        <subdir>FullProcedure</subdir>
        <step aliss='XR1'>Overview.txt</step>
        <step aliss='XR2'>OracleSupportResearch.txt</step>
        <step aliss='XR3'>Install_patch_util.txt</step>
    </group>
</steps>
